import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ScrollNavbar from "./components/global/navbar";
import Footer from "./components/global/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ScrollNavbar/>
      <body className={inter.className}>{children}</body>
      <Footer/>
    </html>
  );
}
